### ISSUE TITLE
Crash on VRCFaceTracking >5.1.0.0

### ISSUE THREAD

**Issue by artifishvr** [dfgHiatus/VRCFT-Babble#2]
On VRCFaceTracking versions >=5.1.0.0 (i think), VRCFT will crash within a couple seconds of launching with the Babble plugin manually installed in Appdata\Roaming\VRCFaceTracking\CustomLibs.

I tested this on:
VRCFT v5.0.2.0 - Works
VRCFT v5.0.2.1 - Works
VRCFT v5.0.2.2 - Works
VRCFT v5.0.2.3 - Works
VRCFT v5.1.0.0 - Crash
VRCFT v5.1.1.0 - Crash
Using plugin version v2.1.0a

Video on VRCFT v5.1.0.0:
https://github.com/dfgHiatus/VRCFT-Babble/assets/59352535/dc4e2ade-bda1-41e8-8bf9-f95ec7f06415

Logs from VRCFT v5.1.0.0:
[latest.log](https://github.com/dfgHiatus/VRCFT-Babble/files/12812002/latest.log)

**Comment by dfgHiatus** [comment]
Fixed in the latest release
