### ISSUE TITLE
Configurable Host and Port for Babble Module

### ISSUE THREAD

**Issue by Amoenus** [dfgHiatus/VRCFT-Babble#4]
# User Story

As a user running VRCFaceTracking (VRCFT) with the Babble module on a Cloud PC, I need the ability to configure the host and port settings of the BabbleOSC component. This will allow me to receive OSC data from my local computer, where Babble is running, to my Cloud PC via a public IP address, not just the loopback (127.0.0.1) IP.

## Use Case

**Scenario:**
1. **Local Computer (Sender):** A user is running Babble software that generates OSC data. This data needs to be sent to a remote Cloud PC.
2. **Cloud PC (Receiver):** The Cloud PC is running VRCFaceTracking (VRCFT) with the Babble module, which listens for OSC data to drive face tracking features.

**Current Limitation:**
- The BabbleOSC component is currently hardcoded to listen on the loopback IP address (127.0.0.1) and a fixed port (8888). This restricts the data flow to within the same machine, preventing communication across different machines.

**Proposed Solution:**
- Modify the BabbleOSC component to accept configurable host and port settings. This will allow the user to specify the IP address and port on which the OSC data should be received, enabling communication over public IP addresses and different network segments.

### Requirements

**Configurable Host and Port:**
   - Update the BabbleOSC constructor to accept both `host` and `port` parameters, with default values of "127.0.0.1" and 8888 respectively.
   - Ensure these parameters are used to bind the socket, allowing the component to listen on the specified IP address and port.

2. **Configuration:**
   - Provide a documentation of how to change configuration or settings file where users can specify the desired host and port.

### Benefits

- **Flexibility:** Users can configure the host and port to match their network setup, allowing seamless integration between local and remote systems.
- **Remote Operation:** Enables scenarios where the local machine generates data and the remote PC processes it
- **Improved User Experience:** Simplifies the process of setting up VRCFT with Babble in diverse environments, making it more accessible and user-friendly.

### Acceptance Criteria

1. The BabbleOSC component must allow configuration of host and port parameters.
2. The component should bind to the specified IP address and port correctly.
3. Documentation must be updated to reflect the new configuration options.
4. Users must be able to configure these settings through a user-friendly interface or configuration file.
5. The system must handle incorrect configurations gracefully, providing meaningful error messages or fallbacks.

**Comment by dfgHiatus** [comment]
Thank you!
